version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./.mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - llmlocal_network

  chat:
    build: .
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017/"
      MODEL_NAME: "EleutherAI/gpt-j-6B"
    healthcheck:
      test: ["CMD-SHELL", "wget http://0.0.0.0:8001/ || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 1s
    depends_on:
      - mongo
    networks:
      - llmlocal_network

networks:
  llmlocal_network: